### ISSUE TITLE
crashes when the network connection is lost.

### ISSUE THREAD

**Issue by gk4** [mfoc/Monitor-Internet-Connection#2]
monitor-internet-connection 1.2.1 running on Raspbian 10 dies when the network becomes unreachable.   The daemon seems to run until the network connection goes down.

Monitoring Internet Connection commencing : 2020-06-04 20:40:34 polling every 20 second(s)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-armv7l/egg/monitor_internet_connection/__main__.py", line 250, in <module>
  File "build/bdist.linux-armv7l/egg/monitor_internet_connection/__main__.py", line 200, in monitor_inet_connection
  File "build/bdist.linux-armv7l/egg/monitor_internet_connection/__main__.py", line 113, in is_internet_alive
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 101] Network is unreachable

**Comment by gk4** [comment]
I will try again using python3

**Comment by mfoc** [comment]
This is not a real issue. 
Why? Because user gk4 was using Python version 2.7.  Both the Github repository readme and the Python Package Index page for monitor_internet_connection states that Python 3.6 or greater is required.  Thus, this issue is closed.
